server:
  port: 8000
  servlet:
    context-path: /

spring:
  application:
    name: url-shortener
  
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=30m,expireAfterWrite=60m
  
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.shorturl: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/url-shortener.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Custom application properties
app:
  url:
    base-domain: localhost:8000
    default-expiry-days: 365
    max-custom-alias-length: 10
    short-url-length: 7
  
  cache:
    url-mappings-ttl: 1800  # 30 minutes
    url-stats-ttl: 3600     # 60 minutes
  
  cleanup:
    expired-urls-cron: "0 0 2 * * ?"  # Run at 2 AM daily