apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  namespace: url-shortener
data:
  application.yml: |
    server:
      port: 8000
      servlet:
        context-path: /

    spring:
      application:
        name: url-shortener
      
      datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          maximum-pool-size: 20
          minimum-idle: 5
          idle-timeout: 300000
          connection-timeout: 20000
          max-lifetime: 1200000
      
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
            use_sql_comments: true
        open-in-view: false
      
      cache:
        type: caffeine
        caffeine:
          spec: maximumSize=10000,expireAfterAccess=30m,expireAfterWrite=60m
      
      jackson:
        time-zone: UTC
        date-format: yyyy-MM-dd HH:mm:ss

    logging:
      level:
        com.shorturl: INFO
        org.springframework.web: INFO
        org.hibernate.SQL: WARN
        org.hibernate.type.descriptor.sql.BasicBinder: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
      metrics:
        export:
          prometheus:
            enabled: true

    app:
      url:
        base-domain: ${BASE_DOMAIN:localhost:8000}
        default-expiry-days: 365
        max-custom-alias-length: 10
        short-url-length: 7
      
      cache:
        url-mappings-ttl: 1800
        url-stats-ttl: 3600
      
      cleanup:
        expired-urls-cron: "0 0 2 * * ?"